baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
    # uncomment line below for temporary local development of module,
    # when using a 'theme' as a git submodule or git cloned files
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[menu]
[[menu.primary]]
    name  = "PMSv3"
    url = "docs/pmsv3/"
    identifier = "pmsv3"
    weight = 10
[[menu.primary]]
    name  = "PLASMA"
    url = "docs/plasma/"
    identifier = "plasma"
    weight = 20
[[menu.primary]]
    name  = "ITP"
    url = "docs/itp/"
    identifier = "itp"
    weight = 30